language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
# Install dependencies
install:
    - "pip install -U . --use-mirrors"
    - "curl https://raw.github.com/sloria/TextBlob/master/download_corpora.py | python"
# Run tests
script: "python run_tests.py"
branches:
    only:
        - master
        - dev